server:
  port: 8080

spring:
  application:
    name: trails-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:mem:trails-db
    username: sa
    password: admin
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  sql:
    init:
      data-locations: classpath:db/populateData.sql
